### PR TITLE
stop all plugin on app quit

### PR DESCRIPTION
**Pull request by Thykof**
- Refactor: move creation of plugin manager
- run all plugin after starting server (plugins register, they need the server to be started)
- stop all plugins on fyne app stop

### CODE REVIEW

**Comment by Pierregvx** [comment]
I had a goroutin error when trying to stop the plugin, I am not sure if it is coming from the wallet or these changes
```
task: Signal received: "interrupt"
[wallet-plugin] Error: [signal SIGSEGV: segmentation violation code=0x1 addr=0x1e000000004 pc=0x7f3521509b6d]

runtime stack:
[wallet-plugin] Error: runtime.throw({0xac4f6b?, 0x7f35214b95c6?})
        /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/panic.go:1047 +0x5d fp=0x7f34ebffe940 sp=0x7f34ebffe910 pc=0x43da7d
runtime.sigpanic()
        /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/signal_unix.go:823 +0x369 fp=0x7f34ebffe990 sp=0x7f34ebffe940 pc=0x453b29

[wallet-plugin] Error: goroutine 68 [syscall]:
runtime.cgocall(0x98e4d0, 0xc00006bfc0)
        /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/cgocall.go:158 +0x5c fp=0xc00006bf98 sp=0xc00006bf60 pc=0x40ba1c
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux._Cfunc_gtk_main_quit()
        _cgo_gotypes.go:1111 +0x45 fp=0xc00006bfc0 sp=0xc00006bf98 pc=0x97c305
[wallet-plugin] Error: github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Window).Quit(...)
        /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/desktop/linux/window.go:342
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).Quit.func1()
        /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/desktop/linux/frontend.go:[wallet-plugin] Error: 339 +0x39 fp=0xc00006bfe0 sp=0xc00006bfc0 pc=0x97f859
[wallet-plugin] Error: runtime.goexit()
        /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00006bfe8 sp=0xc00006bfe0 pc=0x46e941
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).Quit
        /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/desktop/linux/frontend.go:337 +0x6a
```

**Review by peterjah — APPROVED** [review]

**Review by Pierregvx — APPROVED** [review]

**Comment by Thykof** [comment]
@Pierregvx you are right, there is still some issues on ubuntu. Plugins are stopped but Massa Station can't stop, it's stuck at

```
Stopping server...
```

**Comment by Pierregvx** [comment]
> @Pierregvx you are right, there is still some issues on ubuntu. Plugins are stopped but Massa Station can't stop, it's stuck at
> 
> 
> 
> ```
> 
> Stopping server...
> 
> ```

Oh it seemed good when I retested, I'm trying again

**Comment by Pierregvx** [comment]
I see what you meant now, 
```
task: Signal received: "interrupt"
2023-07-03T10:55:26.618+0200    INFO    plugin/manager.go:205   Stopping all plugins...
2023-07-03T10:55:26.621+0200    INFO    api/server.go:126       Stopping server...

```
looks good

**Comment by Thykof** [comment]
it works as expected, I tested with the binary generated by the CI

**Pull request merged**
