### PR TITLE
refactor pkg: make it reusable

### PR DESCRIPTION
**Pull request by Thykof**

### CODE REVIEW

**Review by peterjah — APPROVED** [review]
Good job!
Instead of prepareAddress, i think it would be more accurate to use serializeAddress.

**Comment by SlnPons** [comment]
Can't test, no details.

**Comment by Thykof** [comment]
> Can't test, no details.

it only refactoring the code, I will test no-reg by deploying a flappy on buildnet

**Comment by Thykof** [comment]
here we go! https://flappy.massa/ on buildnet

**Pull request merged**
