### PR TITLE
scrollbar hidden

### PR DESCRIPTION
**Pull request by anubhav1206**

### CODE REVIEW

**Comment by pivilartisant** [comment]
hello @anubhav1206  can you confirm that you we're addressing this issue : https://github.com/massalabs/station/issues/908

**Comment by anubhav1206** [comment]
yes i was

**Comment by pivilartisant** [comment]
> yes i was

cool thank you !

**Review by maxime-carabina — COMMENTED** [review]
Why you want to hidden scrollbar in the home directory ? 🤔

**Comment by maxime-carabina** [comment]
> Why you want to hidden scrollbar in the home directory ? 🤔

@anubhav1206

**Comment by Thykof** [comment]
Hi @anubhav1206 thanks for your contribution! The file you are modifying is in a legacy folder. Sorry we haven't clean up the codebase yet. 

The file you should do the change is https://github.com/massalabs/station/blob/348c29563070c04e821299c500de253d10e518a9/web/massastation/src/index.css#L6-L7

**Comment by SlnPons** [comment]
Hi @anubhav1206 after more than a week of silence, I'll close your PR to avoid confusion and allow others to work on this issue. 
Feel free to give it another try. Cheers.

**Pull request closed without merging**
