### PR TITLE
Update wallet version v0.2.3 in robot test

### PR DESCRIPTION
**Pull request by Thykof**

### CODE REVIEW

**Review by thomas-senechal — APPROVED** [review]

**Comment by thomas-senechal** [comment]
I think we can close this PR in favor of https://github.com/massalabs/station/pull/1133

**Comment by pivilartisant** [comment]
> I think we can close this PR in favor of #1133

Closing

**Comment by longgamma-massa** [comment]
@thomas-senechal need q/a?

**Comment by thomas-senechal** [comment]
> @thomas-senechal need q/a?

No QA needed for things related to unit tests

**Comment by thomas-senechal** [comment]
Furthermore, this PR has been closed in favor of another one

**Pull request closed without merging**
