### PR TITLE
generate certificate with impersonate

### PR DESCRIPTION
**Pull request by Thykof**

### CODE REVIEW

**Review by gregLibert — APPROVED** [review]

**Review by thomas-senechal — APPROVED** [review]

**Comment by gregLibert** [comment]
This is not working and is blocking the install. Here is the extract from the log:

```
MSI (s) (CC:18) [19:12:02:238]: Executing op: ActionStart(Name=GenerateCertificate,,)
Action 19:12:02: GenerateCertificate. 
MSI (s) (CC:18) [19:12:02:244]: Executing op: CustomActionSchedule(Action=GenerateCertificate,ActionType=1058,Source=C:\Program Files (x86)\MassaStation\,Target=cmd /c "C:\Program Files (x86)\MassaStation\generate_certificate.bat",)
MSI (s) (CC:3C) [19:12:02:247]: System Environment : Client has accepted UAC prompt
CustomAction GenerateCertificate returned actual error code 1 (note this may not be 100% accurate if translation happened inside sandbox)
MSI (s) (CC:18) [19:12:03:300]: Note: 1: 1722 2: GenerateCertificate 3: C:\Program Files (x86)\MassaStation\ 4: cmd /c "C:\Program Files (x86)\MassaStation\generate_certificate.bat" 
Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action GenerateCertificate, location: C:\Program Files (x86)\MassaStation\, command: cmd /c "C:\Program Files (x86)\MassaStation\generate_certificate.bat" 
MSI (s) (CC:18) [19:12:27:624]: Product: MassaStation -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action GenerateCertificate, location: C:\Program Files (x86)\MassaStation\, command: cmd /c "C:\Program Files (x86)\MassaStation\generate_certificate.bat" 

Action ended 19:12:27: InstallFinalize. Return value 3.
```

**Comment by Thykof** [comment]
The error in the script is:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129  100   129    0     0    392      0 --:--:-- --:--:-- --:--:--   399
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Failed to open the file mkcert.exe: Permission denied
  0 4781k    0  2742    0     0   2733      0  0:29:51  0:00:01  0:29:50  2733
curl: (23) Failure writing output to destination
"Failed to download mkcert"
```

**Comment by thomas-senechal** [comment]
> The error in the script is:
> 
> ```
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   129  100   129    0     0    392      0 --:--:-- --:--:-- --:--:--   399
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> Warning: Failed to open the file mkcert.exe: Permission denied
>   0 4781k    0  2742    0     0   2733      0  0:29:51  0:00:01  0:29:50  2733
> curl: (23) Failure writing output to destination
> "Failed to download mkcert"
> ```

Because the directory is Read Only. If we change the directory to use, for example a `temp` dir, we won't have the issue and everything should work

**Comment by Thykof** [comment]
@gregLibert should we give it a try or stay with #954 ?

**Pull request merged**
